CREATE DATABASE sportlfc;

USE sportlfc;

-- Creates the table USER and its related attributes
CREATE TABLE USER
(USERID CHAR(9) NOT NULL,
FNAME VARCHAR(18) NOT NULL,
LNAME VARCHAR(18) NOT NULL,
DOB DATE NOT NULL,
SEX CHAR NOT NULL,
PASSWORD VARCHAR(12) NOT NULL,
USER_TYPE VARCHAR(12) NOT NULL,
PRIMARY KEY (USERID));

-- Creates the subclass PLAYER
CREATE TABLE PLAYER
(USERID CHAR(9) NOT NULL,
PRIMARY KEY (USERID));

-- Creates the subclass COACH and its unique attributes
CREATE TABLE COACH
(USERID CHAR(9) NOT NULL,
YRS_OF_EXP VARCHAR(2) NOT NULL,
PRIMARY KEY (USERID));

-- Creates the subclass ADMIN and its unique attributes
CREATE TABLE ADMIN
(USERID CHAR(9) NOT NULL,
IS_ADMIN CHAR NOT NULL,
PRIMARY KEY (USERID));

-- Creates the table EQUIPMENT and its related attributes
CREATE TABLE EQUIPMENT
(EQID CHAR(9) NOT NULL,
NAME VARCHAR(24) NOT NULL,
SIZE VARCHAR(3),
PRICE DECIMAL (5,2) NOT NULL,
PRIMARY KEY (EQID));

-- Creates the table TEAM and its related attributes
CREATE TABLE TEAM
(TEAMID CHAR(9) NOT NULL,
SEX CHAR NOT NULL,
NAME VARCHAR(40) NOT NULL,
MIN_AGE INTEGER NOT NULL,
MAX_AGE INTEGER NOT NULL,
SNAME VARCHAR (20) NOT NULL,
NO_ASSISTANT INT NOT NULL,
PRIMARY KEY (TEAMID));

-- Creates the table SPORT and its related attributes
CREATE TABLE SPORT
(NAME VARCHAR(20) NOT NULL,
MAX_PLAYER INT NOT NULL,
PRIMARY KEY (NAME));

-- Enters in preliminary data to create constraints and foreign keys
INSERT INTO USER (USERID, FNAME, LNAME, DOB, SEX, PASSWORD, USER_TYPE)
VALUES ('123456789', 'Michael', 'Johns', '2005-05-12', 'M', 'ghsdsdf234', 'Player');
INSERT INTO USER (USERID, FNAME, LNAME, DOB, SEX, PASSWORD, USER_TYPE)
VALUES ('432654876', 'Steven', 'Smith', '1989-07-24', 'M', 'sadkfsd54', 'Coach');
INSERT INTO USER (USERID, FNAME, LNAME, DOB, SEX, PASSWORD, USER_TYPE)
VALUES ('542346785', 'Albert', 'Ray', '1992-02-12', 'M', 'msdfdf456', 'Admin');
INSERT INTO TEAM (TEAMID, SEX, NAME, MIN_AGE, MAX_AGE, SNAME, NO_ASSISTANT)
VALUES ('321654987', 'M', 'U13 Blue Saints', '11', '12', 'Basketball', '2');
INSERT INTO EQUIPMENT (EQID, NAME, PRICE)
VALUES('231564879', 'Kneepad', '19.99');
INSERT INTO SPORT (NAME, MAX_PLAYER) 
VALUE ('Basketball', '15');

-- Creation of foreign key constraints
ALTER TABLE TEAM ADD CONSTRAINT
TEAMSPORTFK FOREIGN KEY TEAM(SNAME) REFERENCES SPORT(NAME);
ALTER TABLE COACH ADD CONSTRAINT
COACHUSERFK FOREIGN KEY COACH(USERID) REFERENCES USER(USERID);
ALTER TABLE PLAYER ADD CONSTRAINT
PLAYERUSERFK FOREIGN KEY PLAYER(USERID) REFERENCES USER(USERID);
ALTER TABLE ADMIN ADD CONSTRAINT
ADMINUSERFK FOREIGN KEY ADMIN(USERID) REFERENCES USER(USERID);

-- Creates the table NEEDS for the relationship between EQUIPMENT and SPORT
CREATE TABLE NEEDS
(EQID CHAR(9) NOT NULL,
NAME VARCHAR(12) NOT NULL,
MIN_NUM INTEGER NOT NULL,
PRIMARY KEY(EQID,NAME),
FOREIGN KEY (EQID) REFERENCES EQUIPMENT(EQID),
FOREIGN KEY (NAME) REFERENCES SPORT(NAME));

-- Creates the table PLAYS_IN for the relationship between PLAYER and TEAM
CREATE TABLE PLAYS_IN
(USERID CHAR(9) NOT NULL,
TEAMID CHAR(9) NOT NULL,
UNOFORM_NO VARCHAR(2) NOT NULL,
PRIMARY KEY (USERID, TEAMID),
FOREIGN KEY (USERID) REFERENCES PLAYER(USERID),
FOREIGN KEY (TEAMID) REFERENCES TEAM(TEAMID));

-- Creates the table COACHES for the relationship between COACH and TEAM
CREATE TABLE COACHES
(USERID CHAR(9) NOT NULL,
TEAMID CHAR(9) NOT NULL,
IS_HEAD CHAR NOT NULL,
PRIMARY KEY (USERID, TEAMID),
FOREIGN KEY (USERID) REFERENCES COACH(USERID),
FOREIGN KEY (TEAMID) REFERENCES TEAM(TEAMID));

-- Creates the table BUY for the relationship between PLAYER and EQUIPMENT
CREATE TABLE BUY
(USERID CHAR(9) NOT NULL,
EQID CHAR(9) NOT NULL,
QTY INTEGER NOT NULL,
PRIMARY KEY (USERID, EQID),
FOREIGN KEY (USERID) REFERENCES PLAYER(USERID),
FOREIGN KEY (EQID) REFERENCES EQUIPMENT(EQID));

